<?php

$tasks = $this->tasks;


echo buildTableView($tasks);

function buildTableView(array $tasks): string
{
    ob_start();
    include __DIR__ . '/filterBar.phtml';
    echo '<div class="flex-1 overflow-y-auto w-full">
    <table class="w-full text-sm text-gray-600">
        <thead class="sticky top-0 bg-indigo-200 text-indigo-800">
            <tr class="border-b border-indigo-100">
            <th class="text-left font-medium px-6 py-3 w-[35%]">Description</th>
            <th class="text-left font-medium px-6 py-3 w-[15%]">Status</th>
            <th class="text-left font-medium px-6 py-3 w-[10%]">Start</th>
            <th class="text-left font-medium px-6 py-3 w-[10%]">End</th>
            <th class="text-left font-medium px-6 py-3 w-[20%]">Created By</th>
            <th class="px-6 py-3 w-[10%]"></th>
            </tr>
        </thead>
                
        <tbody class="bg-indigo-50">';
    foreach ($tasks as $index => $task) {
        echo printRowTable($index, $task);
    }
    echo '</tbody>
</table>
</div>';

    return ob_get_clean();
}

function printRowTable(int $index, Task $task): string
{
    ob_start();
    $bgColor = ($index & 1) ? "bg-white" : "";
    echo "<tr class=\"$bgColor border-b border-indigo-100 hover:bg-indigo-100 transition-colors\">" . PHP_EOL;
    echo '<td class="px-6 py-4">' . $task->getDescription() . '</td>' . PHP_EOL;
    echo '<td class="px-6 py-4">
							<span
								class="px-3 py-1 rounded-full text-xs font-medium';
    echo match ($task->getStatusEnum()) {
        Status::PENDING => ' bg-indigo-100 text-indigo-400">' . $task->getStatusEnum()->value . '</span></td>' . PHP_EOL,
        Status::INPROGRESS => ' bg-yellow-100 text-yellow-600">' . $task->getStatusEnum()->value . '</span></td>' . PHP_EOL,
        Status::COMPLETED => ' bg-green-100 text-green-600">' . $task->getStatusEnum()->value . '</span></td>' . PHP_EOL,
    };
    echo '<td class="px-6 py-4">' . $task->getFrom() . '</td>' . PHP_EOL;
    echo '<td class="px-6 py-4">' . $task->getTo() . '</td>' . PHP_EOL;
    echo '<td class="px-6 py-4">' . $task->getCreatedBy() . '</td>' . PHP_EOL;
    echo "<td class=\"px-6 py-4 flex items-center gap-3 \">
							<a href=\"/Alan: ruta por definir/{$task->getId()}\" class=\"text-gray-400 hover:text-indigo-600 transition-colors\">
								<svg xmlns=\"http://www.w3.org/2000/svg\" class=\"w-6 h-6\" fill=\"none\" viewBox=\"0 0 24 24\"
									stroke=\"currentColor\" stroke-width=\"2\">
									<path stroke-linecap=\"round\" stroke-linejoin=\"round\"
										d=\"M15.232 5.232l3.536 3.536M9 13l6.586-6.586a2 2 0 0 1 2.828 2.828L11.828 15.828a2 2 0 0 1-1.414.586H9v-2a2 2 0 0 1 .586-1.414z\" />
								</svg>
							</a>
							<a href=\"/Alan: ruta por definir/{$task->getId()}\" class=\"text-gray-400 hover:text-red-500 transition-colors\">
								<svg xmlns=\"http://www.w3.org/2000/svg\" class=\"w-6 h-6\" fill=\"none\" viewBox=\"0 0 24 24\"
									stroke=\"currentColor\" stroke-width=\"2\">
									<path stroke-linecap=\"round\" stroke-linejoin=\"round\"
										d=\"M19 7l-.867 12.142A2 2 0 0 1 16.138 21H7.862a2 2 0 0 1-1.995-1.858L5 7m5 4v6m4-6v6M9 7h6m2 0a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1m-4 0h10\" />
								</svg>
							</a>
						</td>
					</tr>";
    return ob_get_clean();
}
