<?php

$tasks = $this->_data['tasks'];
if (isset($tasks)) {
    ob_start();
    include __DIR__ . 'filterBar.phtml';
    echo '<div class="flex-1 overflow-y-auto w-full">
    <table class="w-full text-sm text-gray-600">
        <thead class="sticky top-0 bg-indigo-200 text-indigo-800">
            <tr class="border-b border-indigo-100"></tr>
            <th class="text-left font-medium px-6 py-3 w-[35%]">Description</th>
            <th class="text-left font-medium px-6 py-3 w-[15%]">Status</th>
            <th class="text-left font-medium px-6 py-3 w-[10%]">Start</th>
            <th class="text-left font-medium px-6 py-3 w-[10%]">End</th>
            <th class="text-left font-medium px-6 py-3 w-[20%]">Created By</th>
            <th class="px-6 py-3 w-[10%]"></th>
        </thead>
                
        <tbody class="bg-indigo-50">';
    foreach ($tasks as $task) {
        echo $task->printRowTable(); //Edwin Barrera: To be built
    }
    echo '</tbody>
</table>
</div>';
}
